### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by metzger100** [e-sailing/openplotter-avnav#4]
I installed Avnav and after openning the Browser tells me that the Site can't be found. I did reinstall it but the Issue is still there.

**Comment by e-sailing** [comment]
Please look if the processs is running. 
Use the Avnav button to open avnav (it does use the right port).
There could be another process using the port 8080. Switch to another one. Apply Changes. Restart Avnav process and try again.

**Comment by metzger100** [comment]
Thanks for your help. I am using a Raspberry Pi 4 with openplotter-avnav now, which works perfect. I don't know why it didn't work on the Rpi3. Thank you for your work.
