### ISSUE TITLE
Wellenvogel/avnav update

### ISSUE THREAD

**Issue by Jamos1988** [e-sailing/openplotter-avnav#5]
Hi, https://github.com/wellenvogel/avnav (original developer) just did an update so SignalK charts are supported:

https://www.wellenvogel.net/software/avnav/downloads/release/20201105/fr 

More info: https://github.com/wellenvogel/avnav/issues/72#issuecomment-691919324

I used the e-saling / openplotter installation, how can I upgrade so this new features is enabled?

**Comment by e-sailing** [comment]
Now avnav and openplotter-avnav should update with 
sudo apt update 
sudo apt upgrade.

**Comment by Jamos1988** [comment]
Fixed!
Just one thing, the avnav-installer I can change the port which the webserver will broadcast. However, I cannot change it to anything other than 8080. It saves, but it will still open at port 8080. I I need to create a separate issue, let me know.

**Comment by Jamos1988** [comment]
Extra information, on port 8081 I get the standard jetty9 welcome screen rather than avnav. However, I have disabled jett9 with sudo systemctl disable jetty9 so I didn't expect this problem anymore.

**Comment by Jamos1988** [comment]
Fixed!
